version: "3"
services:
  ffmpeg:
    image: "linuxserver/ffmpeg"
    volumes:
      - ./videos:/videos
    command: "-fflags nobuffer \
      -rtsp_transport tcp \
      -i $RTSP_STREAM \
      -vsync 0 \
      -copyts \
      -vcodec copy \
      -movflags frag_keyframe+empty_moov \
      -hls_flags delete_segments+append_list \
      -f segment \
      -segment_list_flags live \
      -segment_time 3 \
      -segment_list_size 2 \
      -segment_format mpegts \
      -segment_list /videos/index.m3u8 \
      -segment_list_type m3u8 \
      -segment_list_entry_prefix / \
      /videos/%3d.ts"
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./videos:/usr/src/app/videos
    depends_on:
      - ffmpeg
